targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        options:
          dart2js_args:
            - -O4
            - --minify
            - --fast-startup
            - --no-source-maps
            - --csp
