name: HolySheetWeb
description: A web app for HolySheet
version: 1.0.0
homepage: https://holysheet.org/
author: RubbaBoy <adam@yarr.is>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_router: ^2.0.0-alpha
  angular_components: ^0.14.0-alpha+1
  bootstrap_sass: any
  js: ^0.6.1+1
  grpc: ^2.1.3
  protoc_plugin: any
  fixnum: ^0.10.11
  filesize: ^1.0.4

dev_dependencies:
  angular_test: ^2.4.0
  build_runner: ^1.7.3
  build_test: ^0.10.11
  build_web_compilers: ^2.8.0
  pedantic: ^1.9.0
  test: ^1.11.0
  sass_builder: ^2.1.3

# pub run build_runner serve web:8090
# pub run build_runner build
